# Generated by Django 5.0.1 on 2024-02-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_position_post_sort_alter_author_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sort',
            new_name='post_type',
        ),
    ]
