# Generated by Django 5.0.1 on 2024-02-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_subscribers_author_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subs',
            field=models.ManyToManyField(through='news.Subscribers', to='news.author'),
        ),
    ]
